# Generated by Django 4.2.5 on 2023-09-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_alter_chatmodel_id_alter_chatnotification_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofilemodel", name="user",),
        migrations.DeleteModel(name="ChatNotification",),
        migrations.DeleteModel(name="UserProfileModel",),
    ]
