# Generated by Django 4.2.5 on 2023-09-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0008_thread_message"),
    ]

    operations = [
        migrations.RemoveField(model_name="thread", name="thread_type",),
    ]
